model: debug # release debug
server:
  ip: 127.0.0.1
  port: 8090
  name: order_center
  ticker: 5 #min
rabbitmq:
  name: logic.rabbitmq
  user: admin
  pwd: admin
mysql:
  host: host
  port: 3306
  user: user
  pwd: pwd
  db_name: order_center
  charset: utf8mb4
  conn_max_lifetime: 5
  max_idle_conns: 10
  max_Open_conns: 140
  disable_foreign_key_constraint_when_migrating: false
log:
  access_path: ./log/access_log.txt
  error_path: ./log/error_log.txt
etcd:
  ttl: 10
  ip: 127.0.0.1
  port: 2379
waybill_center:
  name: waybill_center
  name_service: logic.waybill_center
